camunda:
  bpm:
    admin-user:
      id: demo
      password: 123
      first-name: Demo_Account
    filter:
      create: All tasks

application:
  api:
    weather:
      url: 'localhost:8080/api/v1/weather'

server:
  port: ${CAMUNDA_SERVER_PORT:8080}